### PR TITLE
chore: refactored model deployment. Switching to a leaner image for a dev container

### PR DESCRIPTION
**Pull request by romaniam**
## Refactoring
Remove requirements.txt from project root and made step02 self contained using poetry 

## Dev container improvements 

Replace python image with python alpine reducing the startup time of dev container and the total image size.

**Before:**
before

**After:**
alpine

The image size was reduced from 2GB to approx. 500mb

Since each step is now self contained it's no longer needed to installed unused dependencies during container startup which results in faster startup time

### CODE REVIEW

**Comment by rui1610** [comment]
This is fantastic work! Thanks a lot! I'm a big fan of Alpine as well and will review properly. Not 100% sure about poetry so far (haven't used it so far), but will give it a fair chance! 
Due to the amount of changed files, I'll need some time to review deeply as this is a major change. Therefore, please give me one or two days for the review.

Again thanks @romaniam, @SeriousSem  and @EvgeniiSkrebtcov for this PR!

**Review by rui1610 — CHANGES_REQUESTED** [review]
The example "03_vision_model" doesn't run. Getting errors 
```
ERROR  : pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  No deployment found with: deployment.deployment_id == None, deployment.config_id == None, deployment.config_name == None, deployment.model_name == gpt-4o (type=value_error)"
```

In example "04_rag_on_mixed_data" I'm getting errors as well: 
```
ERROR  : Ingesting unstructured data failed: 1 validation error for ChatOpenAI
__root__
  No deployment found with: deployment.deployment_id == None, deployment.config_id == None, deployment.config_name == None, deployment.model_name == gpt-4o (type=value_error)
```
  
In addition I'm wondering how we will ensure, that the various libs in each pyproject.toml can be kept up-to-data. With the currently used approach using "pip-compile" the right versions where setup automatically and hence we could run a github action to automatically create a PR with the up-to-date versions for each lib.
How can we do this as well with poetry? If we can't the repo will be very difficult to be maintained by the (small) team of this repo.

**Comment by EvgeniiSkrebtcov** [comment]
@rui1610 , I updated the list of models that are mentioned in the btp_ai_setup.tfvars. Please update your local file as well: `target_ai_core_model = ["gpt-35-turbo", "text-embedding-ada-002", "anthropic--claude-3-sonnet", "gpt-4o"]`

**Comment by EvgeniiSkrebtcov** [comment]
@rui1610 , I proposed the dependabot configuration update to cover poetry dependencies in subfolders based on the `directories` option and a [wildcard support](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories:~:text=interval%3A%20%22weekly%22-,directories,-Required.%20You%20must).

**Review by rui1610 — APPROVED** [review]
Lgtm.
Thanks a lot for the great work!

**Pull request merged**
